# Nome do Workflow do GitHub Actions
name: Generate Snake Animation

# Controles de quando a action será executada
on:
  # Executa automaticamente a cada 12 horas
  schedule:
    - cron: '0 */12 * * *'
  
  # Permite que você execute esta action manualmente a partir da aba Actions
  workflow_dispatch:

# Uma única tarefa (job) chamada "build" que fará todo o trabalho
jobs:
  build:
    # O tipo de máquina virtual para executar a tarefa
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do seu repositório para que a action possa acessá-lo
      - uses: actions/checkout@v4

      # 2. Gera a animação da serpente
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # O seu nome de usuário do GitHub (usa uma variável automática para não precisar escrever)
          github_user_name: ${{ github.repository_owner }}
          
          # Lista de saídas a serem geradas. O arquivo SVG será salvo em 'dist/'
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3. Envia os arquivos gerados para o branch 'output'
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # O branch para o qual os arquivos serão enviados
          target_branch: output
          # O diretório que contém os arquivos a serem enviados (deve corresponder à saída do passo anterior)
          build_dir: dist
        env:
          # Token de acesso automático fornecido pelo GitHub para permitir o push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
