name: Generate Snake Animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  build:
    name: Generate and Publish Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Generate Snake Animation
      - name: Generate Snake SVG
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: cerqueiracesar
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
